---
- name: Validar sshd
  ansible.builtin.command: sshd -t
  changed_when: false

- name: Recargar sshd
  ansible.builtin.systemd:
    name: ssh
    state: reloaded

- name: Aplicar sysctl
  ansible.builtin.command: sysctl --system
  changed_when: false
