---
k3s_cni_calico_version: v3.33.0
k3s_cni_cilium_version: v1.20.2
k3s_cni_canal_manifest_url: >-
  https://raw.githubusercontent.com/projectcalico/calico/{{ k3s_cni_calico_version }}/manifests/canal.yaml
k3s_cni_calico_crds_url: >-
  https://raw.githubusercontent.com/projectcalico/calico/{{ k3s_cni_calico_version }}/manifests/operator-crds.yaml
k3s_cni_calico_operator_url: >-
  https://raw.githubusercontent.com/projectcalico/calico/{{ k3s_cni_calico_version }}/manifests/tigera-operator.yaml
