---
- name: Instalar unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
    update_cache: true

- name: Habilitar actualizaciones de seguridad automaticas
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: "0644"
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";

- name: Solo parches de seguridad en unattended-upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: "0644"
    content: |
      Unattended-Upgrade::Allowed-Origins {
          "${distro_id}:${distro_codename}-security";
      };
      Unattended-Upgrade::Automatic-Reboot "true";
      Unattended-Upgrade::Automatic-Reboot-Time "{{ k3s_install.os_hardening.reboot_schedule[inventory_hostname] | default('04:30') }}";

- name: Habilitar servicio unattended-upgrades
  ansible.builtin.systemd:
    name: unattended-upgrades
    enabled: true
    state: started
